channels:
  # Define conda channels here. 
  - conda-forge

dependencies:
  # Define conda packages here. 
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search  
  - python=3.7.5

  - pip=20.1
  - pip:
    # Define pip packages here. 
    # https://pypi.org/
    - rpaframework==11.4.0 # https://rpaframework.org/releasenotes.html
    - appdirs==1.4.4
    - async-generator==1.10
    - attrs==21.2.0
    - Authlib==0.15.5
    - backports.zoneinfo==0.2.1
    - beautifulsoup4==4.10.0
    - bs4==0.0.1
    - cached-property==1.5.2
    - certifi==2021.10.8
    - cffi==1.15.0
    - chardet==3.0.4
    - charset-normalizer==2.0.7
    - click==7.1.2
    - colorama==0.4.4
    - configparser==5.0.2
    - crayons==0.4.0
    - cryptography==35.0.0
    - decorator==5.1.0
    - defusedxml==0.7.1
    - dnspython==2.1.0
    - docutils==0.18.1
    - et-xmlfile==1.1.0
    - exchangelib==4.6.1
    - fpdf2==2.4.6
    - furl==2.1.3
    - graphviz==0.13.2
    - h11==0.12.0
    - htmldocx==0.0.6
    - idna==3.3
    - importlib-resources==5.4.0
    - isodate==0.6.0
    - java-access-bridge-wrapper==0.7.5
    - jsonpath-ng==1.5.3
    - jsonschema==4.2.1
    - lxml==4.6.4
    - mss==6.1.0
    - netsuitesdk==1.24.0
    - notifiers==1.2.1
    - ntlm-auth==1.5.0
    - numpy==1.21.4
    - oauthlib==3.1.1
    - openpyxl==3.0.9
    - orderedmultidict==1.0.1
    - outcome==1.1.0
    - pandas==1.3.4
    - pdfminer.six==20200517
    - pdfplumber==0.5.28
    - Pillow==8.4.0
    - platformdirs==2.4.0
    - ply==3.11
    - proxy-tools==0.1.0
    - pycparser==2.20
    - pycryptodome==3.12.0
    - Pygments==2.10.0
    - pynput-robocorp-fork==4.0.0
    - pyOpenSSL==21.0.0
    - PyPDF2==1.26.0
    - pyperclip==1.8.2
    - PyQt5==5.15.6
    - PyQt5-Qt5==5.15.2
    - PyQt5-sip==12.9.0
    - PyQtWebEngine==5.15.5
    - PyQtWebEngine-Qt5==5.15.2
    - pyrsistent==0.18.0
    - PySocks==1.7.1
    - python-dateutil==2.8.2
    - python-docx==0.8.11
    - python-xlib==0.31
    - pytz==2021.3
    - pywebview==3.5
    - PyYAML==5.4.1
    - requests==2.26.0
    - requests-file==1.5.1
    - requests-ntlm==1.1.0
    - requests-oauthlib==1.3.0
    - requests-toolbelt==0.9.1
    - rfc3987==1.3.8
    - robocorp-dialog==0.4.1
    - robotframework==4.1.2
    - robotframework-pythonlibcore==3.0.0
    - robotframework-requests==0.9.2
    - robotframework-seleniumlibrary==5.1.3
    - robotframework-seleniumtestability==1.1.0
    - rpa==1.45.0
    - rpaframework-core==6.5.1
    - rpaframework-dialogs==0.4.2
    - rpaframework-pdf==1.30.2
    - selenium==4.0.0
    - simple-salesforce==1.11.4
    - six==1.16.0
    - sniffio==1.2.0
    - sortedcontainers==2.4.0
    - soupsieve==2.2.1
    - tagui==1.45.0
    - tenacity==8.0.1
    - tqdm==4.62.3
    - trio==0.19.0
    - trio-websocket==0.9.2
    - tweepy==3.10.0
    - tzdata==2021.5
    - tzlocal==2.1
    - urllib3==1.26.7
    - Wand==0.6.7
    - webdriver-manager==3.5.1
    - webdrivermanager==0.10.0
    - wrapt==1.13.3
    - wsproto==1.0.0
    - xlrd==2.0.1
    - XlsxWriter==3.0.2
    - xlutils==2.0.0
    - xlwt==1.3.0
    - zeep==4.1.0
    - zipp==3.6.0